#!/usr/bin/env python3

import openai, os, configparser, argparse, sys

def main(engine, msg, CHATGPT_KEY):
    openai.api_key = CHATGPT_KEY
    # print(openai.Model.list())
    response = openai.Completion.create(
        engine = str(engine),
        prompt = str(msg),
        max_tokens = 1024,
        n = 1,
        stop = None,
        temperature = 0.8
    )
    print(response["choices"][0]["text"])

if __name__ == "__main__":
    config = configparser.ConfigParser()
    try:
        config.read(os.path.expanduser('~')+'/.chatgpt')
        CHATGPT_KEY = config.get('DEFAULT', 'key')
    except:
        print('Error reading ~/.chatgpt file.')
    
    parser = argparse.ArgumentParser(
        prog="chatgpt-cli", description="Send question to chatgpt through cli")
    parser.add_argument('--engine', '-e', nargs='?', help="select various engine from the chatpt", default='davinci')
    parser.add_argument('--msg', '-m', nargs='?', help="Define message, user input should end with `Ctrd + d` or send it through pipe.")


    if not sys.stdin.isatty():
        msg = sys.stdin.read()
        args = parser.parse_args()
        main(args.engine, msg, CHATGPT_KEY)
    else:
        args = parser.parse_args()
        main(args.engine, args.msg, CHATGPT_KEY)